# MkDocs configuration for CreatureGRC documentation
# Integrated with Backstage TechDocs

site_name: CreatureGRC
site_description: Open-source compliance automation platform
site_url: https://yokoszn.github.io/CreatureGRC
repo_url: https://github.com/yokoszn/CreatureGRC
repo_name: yokoszn/CreatureGRC
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - techdocs-core
  - mkdocstrings:
      handlers:
        python:
          paths: [src, packages]
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quickstart.md
    - Installation: installation.md
    - Configuration: configuration.md
  - User Guide:
    - Commands: commands.md
    - Agent Mode: agent-mode.md
    - Server Mode: server-mode.md
    - Profile Management: profile-management.md
  - Integrations:
    - Overview: integrations/overview.md
    - Netbox: integrations/netbox.md
    - Wazuh: integrations/wazuh.md
    - Keycloak: integrations/keycloak.md
    - Cloud/SaaS: integrations/cloud-saas.md
  - Architecture:
    - Overview: architecture/overview.md
    - Workspace Structure: architecture/workspace.md
    - Configuration System: architecture/configuration.md
    - Plugin System: architecture/plugins.md
    - Creature IR: architecture/creature-ir.md
  - Architecture Decisions:
    - ADR-001: Configuration Architecture: adr/001-configuration-architecture.md
  - Development:
    - Contributing: contributing.md
    - Development Setup: development/setup.md
    - Creating Plugins: development/creating-plugins.md
    - Testing: development/testing.md
    - Release Process: development/releases.md
  - API Reference:
    - CLI: api/cli.md
    - REST API: api/rest.md
    - Creature IR Models: api/creature-ir.md
    - Configuration: api/configuration.md
  - Deployment:
    - Docker Compose: deployment/docker-compose.md
    - Kubernetes: deployment/kubernetes.md
    - Security: deployment/security.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yokoszn/CreatureGRC
  version:
    provider: mike
