[project]
name = "creature-ir"
version = "2.0.0"
description = "CreatureGRC intermediate representation - the only stable contract"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/creature_ir"]
